# Generated by Django 3.2.7 on 2021-09-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'My Blog', 'verbose_name_plural': 'My Blogs'},
        ),
    ]
